// <auto-generated />
using System;
using Lomboque.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lomboque.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220131095834_initApp")]
    partial class initApp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Lomboque.Domain.Entities.Observasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Jam")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Tanggal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LarikObservasi");
                });

            modelBuilder.Entity("Lomboque.Domain.Entities.Pot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KelembabanTanah")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObservasiId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SuhuUdara")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ObservasiId");

                    b.ToTable("Pot");
                });

            modelBuilder.Entity("Lomboque.Domain.Entities.Pot", b =>
                {
                    b.HasOne("Lomboque.Domain.Entities.Observasi", null)
                        .WithMany("LarikPot")
                        .HasForeignKey("ObservasiId");
                });

            modelBuilder.Entity("Lomboque.Domain.Entities.Observasi", b =>
                {
                    b.Navigation("LarikPot");
                });
#pragma warning restore 612, 618
        }
    }
}
