// <auto-generated />
using System;
using Lomboque.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lomboque.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Lomboque.Domain.Entities.Observasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Jam")
                        .HasColumnType("TEXT");

                    b.Property<int>("KelembabanTanah")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NomorPot")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SuhuUdara")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("Tanggal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Observasi");
                });
#pragma warning restore 612, 618
        }
    }
}
